server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JnCaoxia/springcloudconfiggit/   # 配置git仓库的地址
          search-paths: config-repo                               # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: jn_caoxia@163.com                             # git仓库的账号
          password: 283173caoxia                                  # git仓库的密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: caox
    password: caox
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/     # # 注册中心eurka地址

management:
  security:
     enabled: false
