server:
  port: 8001
spring:
  application:
    name: admin-server
  mail:
      host: smtp.qq.com
      username:
      password:
      properties:
        mail:
          smtp:
            auth: true
            starttls:
                enable: true
                required: true
      boot:
          admin:
            notify:
              mail:
                from:
                to:
      default-encoding: UTF-8
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  security:
    enabled: false


